### ISSUE TITLE
Test bin exists

### ISSUE THREAD

**Issue by kshji** [DDoctorzeus/GAShell#1]
Better method test if some bin exists, example using hash command. It use your PATH variable. 
```
if ! hash oathtool 2>/dev/null ; then
        echo "Please ensure that oathtool is installed!" >&2
        exit 2
fi
```

```

CONFIGDIR="$HOME/.config/gashell"
QRWEBOUTPUT="/tmp/$USER.gashellqr.file"
ERROROUTFILE="/tmp/$USER.gashellerr.txt"

```
You don't need ; at end of line if you have only one cmd / line.

**Comment by DDoctorzeus** [comment]
Thanks, will look into changing this next update.

Yes but I know but it helps with code editing (at least for me).
