### ISSUE TITLE
CONFIGDIR seems incorrect

### ISSUE THREAD

**Issue by ebydj1** [DDoctorzeus/GAShell#3]
The way CONFIGDIR sets the home directory in the shell script seems incorrect. I think it should use $HOME rather than /home/$USER, as the home directory for a new user can be specified arbitrarily. $HOME should be safe, see https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html and search for HOME.

**Comment by ebydj1** [comment]
Created pull request #4 to address this issue.

**Comment by DDoctorzeus** [comment]
Thanks for catching that!

Have merged to base branch.
