### ISSUE TITLE
Migrate to another device?

### ISSUE THREAD

**Issue by irwsrs** [DDoctorzeus/GAShell#5]
This is probably not an _issue_ as being able to do this too easily would be an obvious security risk, but I want to sync my keys to another device. If I rsync `.config/gashell/` the target device will indeed display codes with the same names, but the codes will be different. Is there any way to do this without starting from scratch on the new device?

**Comment by DDoctorzeus** [comment]
Sorry I somehow managed to completely miss the issue notification!

As long as you copy the $HOME/.config/gashell config directory to the same location on the new device, the codes generated should be the same..

Code generation depends on the system time, it doesn't take any sort of hardware UUIDs etc.. I would try syncing both systems using an NTP server and see if the codes generated are the same then?
